<?php

namespace Database\Seeders;

use App\Models\SubCounty;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubCountySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SubCounty::truncate();

        $subcounties =  [
            [
                'name' => 'Changamwe',
                'county_id'=> 1,
                'code' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jomvu',
                'county_id'=> 1,
                'code' => '002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kisauni',
                'county_id'=> 1,
                'code' => '003',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyali',
                'county_id'=> 1,
                'code' => '004',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Likoni',
                'county_id'=> 1,
                'code' => '005',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mvita',
                'county_id'=> 1,
                'code' => '006',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Msambweni',
                'county_id'=> 2,
                'code' => '007',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lunga Lunga',
                'county_id'=> 2,
                'code' => '008',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Matuga',
                'county_id'=> 2,
                'code' => '009',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kinango',
                'county_id'=> 2,
                'code' => '010',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kilifi North',
                'county_id'=> 3,
                'code' => '011',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kilifi South',
                'county_id'=> 3,
                'code' => '012',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kaloleni',
                'county_id'=> 3,
                'code' => '013',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rabai',
                'county_id'=> 3,
                'code' => '014',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ganze',
                'county_id'=> 3,
                'code' => '015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Malindi',
                'county_id'=> 3,
                'code' => '016',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Magarini',
                'county_id'=> 3,
                'code' => '017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Garsen',
                'county_id'=> 4,
                'code' => '018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Galole',
                'county_id'=> 4,
                'code' => '019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bura',
                'county_id'=> 4,
                'code' => '020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lamu East',
                'county_id'=> 5,
                'code' => '021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lamu West',
                'county_id'=> 5,
                'code' => '022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Taveta',
                'county_id'=> 6,
                'code' => '023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wundanyi',
                'county_id'=> 6,
                'code' => '024',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mwatate',
                'county_id'=> 6,
                'code' => '025',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Voi',
                'county_id'=> 6,
                'code' => '026',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Garissa Township',
                'county_id'=> 7,
                'code' => '027',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Balambala',
                'county_id'=> 7,
                'code' => '028',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lagdera',
                'county_id'=> 7,
                'code' => '029',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dadaab',
                'county_id'=> 7,
                'code' => '030',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fafi',
                'county_id'=> 7,
                'code' => '031',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ijara',
                'county_id'=> 7,
                'code' => '032',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wajir North',
                'county_id'=> 8,
                'code' => '033',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wajir East',
                'county_id'=> 8,
                'code' => '034',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tarbaj',
                'county_id'=> 8,
                'code' => '035',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wajir West',
                'county_id'=> 8,
                'code' => '036',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eldas',
                'county_id'=> 8,
                'code' => '037',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wajir South',
                'county_id'=> 8,
                'code' => '038',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mandera West',
                'county_id'=> 9,
                'code' => '039',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Banisa',
                'county_id'=> 9,
                'code' => '040',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mandera North',
                'county_id'=> 9,
                'code' => '041',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mandera South',
                'county_id'=> 9,
                'code' => '042',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mandera East',
                'county_id'=> 9,
                'code' => '043',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lafey',
                'county_id'=> 9,
                'code' => '044',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Moyale',
                'county_id'=> 10,
                'code' => '045',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'North Horr',
                'county_id'=> 10,
                'code' => '046',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Saku',
                'county_id'=> 10,
                'code' => '047',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laisamis',
                'county_id'=> 10,
                'code' => '048',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isiolo North',
                'county_id'=> 11,
                'code' => '049',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isiolo South',
                'county_id'=> 11,
                'code' => '050',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Igembe South',
                'county_id'=> 12,
                'code' => '051',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Igembe Central',
                'county_id'=> 12,
                'code' => '052',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Igembe North',
                'county_id'=> 12,
                'code' => '053',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tigania West',
                'county_id'=> 12,
                'code' => '054',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tigania East',
                'county_id'=> 12,
                'code' => '055',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'North Imenti',
                'county_id'=> 12,
                'code' => '056',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Buuri',
                'county_id'=> 12,
                'code' => '057',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Central Imenti',
                'county_id'=> 12,
                'code' => '058',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'South Imenti',
                'county_id'=> 12,
                'code' => '059',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Maara',
                'county_id'=> 13,
                'code' => '060',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chuka / Igambang’ombe',
                'county_id'=> 13,
                'code' => '061',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tharaka',
                'county_id'=> 13,
                'code' => '062',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Manyatta',
                'county_id'=> 14,
                'code' => '063',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Runyenjes',
                'county_id'=> 14,
                'code' => '064',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mbeere South',
                'county_id'=> 14,
                'code' => '065',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mbeere North',
                'county_id'=> 14,
                'code' => '066',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mwingi North',
                'county_id'=> 20,
                'code' => '067',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mwingi West',
                'county_id'=> 20,
                'code' => '068',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mwingi Central',
                'county_id'=> 20,
                'code' => '069',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitui West',
                'county_id'=> 20,
                'code' => '070',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitui Rural',
                'county_id'=> 20,
                'code' => '071',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitui Central',
                'county_id'=> 20,
                'code' => '072',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitui East',
                'county_id'=> 20,
                'code' => '073',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitui South',
                'county_id'=> 20,
                'code' => '074',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Masinga',
                'county_id'=> 21,
                'code' => '075',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yatta',
                'county_id'=> 21,
                'code' => '076',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kangundo',
                'county_id'=> 21,
                'code' => '077',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Matungulu',
                'county_id'=> 21,
                'code' => '078',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kathiani',
                'county_id'=> 21,
                'code' => '079',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mavoko',
                'county_id'=> 21,
                'code' => '080',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Machakos Town',
                'county_id'=> 21,
                'code' => '081',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mwala',
                'county_id'=> 21,
                'code' => '082',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mbooni',
                'county_id'=> 22,
                'code' => '083',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kilome ',
                'county_id'=> 22,
                'code' => '084',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kaiti',
                'county_id'=> 22,
                'code' => '085',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Makueni',
                'county_id'=> 22,
                'code' => '086',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kibwezi West',
                'county_id'=> 22,
                'code' => '087',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kibwezi East',
                'county_id'=> 22,
                'code' => '088',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kinangop',
                'county_id'=> 15,
                'code' => '089',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kipipiri',
                'county_id'=> 15,
                'code' => '090',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ol Kalou',
                'county_id'=> 15,
                'code' => '091',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ol Jorok',
                'county_id'=> 15,
                'code' => '092',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ndaragwa',
                'county_id'=> 15,
                'code' => '093',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tetu',
                'county_id'=> 16,
                'code' => '094',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kieni',
                'county_id'=> 16,
                'code' => '095',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mathira',
                'county_id'=> 16,
                'code' => '096',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Othaya',
                'county_id'=> 16,
                'code' => '097',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mukurwe-Ini',
                'county_id'=> 16,
                'code' => '098',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyeri Town',
                'county_id'=> 16,
                'code' => '099',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mwea',
                'county_id'=> 17,
                'code' => '100',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gichugu',
                'county_id'=> 17,
                'code' => '101',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ndia',
                'county_id'=> 17,
                'code' => '102',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kirinyaga Central',
                'county_id'=> 17,
                'code' => '103',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kangema',
                'county_id'=> 18,
                'code' => '104',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => ' Mathioya',
                'county_id'=> 18,
                'code' => '105',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kiharu',
                'county_id'=> 18,
                'code' => '106',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kigumo',
                'county_id'=> 18,
                'code' => '107',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Maragua',
                'county_id'=> 18,
                'code' => '108',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kandara',
                'county_id'=> 18,
                'code' => '109',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gatanga',
                'county_id'=> 18,
                'code' => '110',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gatundu South',
                'county_id'=> 19,
                'code' => '111',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gatundu North',
                'county_id'=> 19,
                'code' => '112',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Juja',
                'county_id'=> 19,
                'code' => '113',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Thika Town',
                'county_id'=> 19,
                'code' => '114',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ruiru',
                'county_id'=> 19,
                'code' => '115',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Githunguri',
                'county_id'=> 19,
                'code' => '116',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kiambu',
                'county_id'=> 19,
                'code' => '117',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kiambaa',
                'county_id'=> 19,
                'code' => '118',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kabete',
                'county_id'=> 19,
                'code' => '119',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kikuyu',
                'county_id'=> 19,
                'code' => '120',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Limuru',
                'county_id'=> 19,
                'code' => '121',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lari',
                'county_id'=> 19,
                'code' => '122',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turkana North',
                'county_id'=> 23,
                'code' => '123',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turkana West',
                'county_id'=> 23,
                'code' => '124',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turkana Central',
                'county_id'=> 23,
                'code' => '125',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Loima',
                'county_id'=> 23,
                'code' => '126',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turkana South',
                'county_id'=> 23,
                'code' => '127',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turkana East',
                'county_id'=> 23,
                'code' => '128',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kapenguria',
                'county_id'=> 24,
                'code' => '129',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sigor',
                'county_id'=> 24,
                'code' => '130',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kacheliba',
                'county_id'=> 24,
                'code' => '131',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pokot South',
                'county_id'=> 24,
                'code' => '132',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Samburu West',
                'county_id'=> 25,
                'code' => '133',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Samburu North',
                'county_id'=> 25,
                'code' => '134',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Samburu East',
                'county_id'=> 25,
                'code' => '135',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kwanza',
                'county_id'=> 26,
                'code' => '136',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Endebess',
                'county_id'=> 26,
                'code' => '137',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Saboti',
                'county_id'=> 26,
                'code' => '138',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kiminini',
                'county_id'=> 26,
                'code' => '139',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cherangany',
                'county_id'=> 26,
                'code' => '140',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Soy',
                'county_id'=> 27,
                'code' => '141',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turbo',
                'county_id'=> 27,
                'code' => '142',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Moiben',
                'county_id'=> 27,
                'code' => '143',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ainabkoi',
                'county_id'=> 27,
                'code' => '144',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kapseret',
                'county_id'=> 27,
                'code' => '145',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kesses',
                'county_id'=> 27,
                'code' => '146',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Marakwet East',
                'county_id'=> 28,
                'code' => '147',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Marakwet West',
                'county_id'=> 28,
                'code' => '148',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keiyo North',
                'county_id'=> 28,
                'code' => '149',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keiyo South',
                'county_id'=> 28,
                'code' => '150',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tinderet',
                'county_id'=> 29,
                'code' => '151',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aldai',
                'county_id'=> 29,
                'code' => '152',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nandi Hills',
                'county_id'=> 29,
                'code' => '153',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chesumei',
                'county_id'=> 29,
                'code' => '154',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emgwen',
                'county_id'=> 29,
                'code' => '155',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mosop',
                'county_id'=> 29,
                'code' => '156',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tiaty',
                'county_id'=> 30,
                'code' => '157',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baringo North',
                'county_id'=> 30,
                'code' => '158',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baringo Central',
                'county_id'=> 30,
                'code' => '159',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baringo South',
                'county_id'=> 30,
                'code' => '160',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mogotio',
                'county_id'=> 30,
                'code' => '161',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eldama Ravine',
                'county_id'=> 30,
                'code' => '162',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laikipia West',
                'county_id'=> 31,
                'code' => '163',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laikipia East',
                'county_id'=> 31,
                'code' => '164',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laikipia North',
                'county_id'=> 31,
                'code' => '165',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Molo',
                'county_id'=> 32,
                'code' => '166',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Njoro',
                'county_id'=> 32,
                'code' => '167',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Naivasha',
                'county_id'=> 32,
                'code' => '168',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gilgil',
                'county_id'=> 32,
                'code' => '169',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kuresoi South',
                'county_id'=> 32,
                'code' => '170',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kuresoi North',
                'county_id'=> 32,
                'code' => '171',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Subukia',
                'county_id'=> 32,
                'code' => '172',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rongai',
                'county_id'=> 32,
                'code' => '173',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bahati',
                'county_id'=> 32,
                'code' => '174',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nakuru Town West',
                'county_id'=> 32,
                'code' => '175',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nakuru Town East',
                'county_id'=> 32,
                'code' => '176',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kilgoris',
                'county_id'=> 33,
                'code' => '177',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emurua Dikirr',
                'county_id'=> 33,
                'code' => '178',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Narok North',
                'county_id'=> 33,
                'code' => '179',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Narok East',
                'county_id'=> 33,
                'code' => '180',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Narok South',
                'county_id'=> 33,
                'code' => '181',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Narok West',
                'county_id'=> 33,
                'code' => '182',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kajiado North',
                'county_id'=> 34,
                'code' => '183',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kajiado Central',
                'county_id'=> 34,
                'code' => '184',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kajiado East',
                'county_id'=> 34,
                'code' => '185',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kajiado West',
                'county_id'=> 34,
                'code' => '186',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kajiado South',
                'county_id'=> 34,
                'code' => '187',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kipkelion East',
                'county_id'=> 35,
                'code' => '188',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kipkelion West',
                'county_id'=> 35,
                'code' => '189',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ainamoi',
                'county_id'=> 35,
                'code' => '190',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bureti',
                'county_id'=> 35,
                'code' => '191',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Belgut',
                'county_id'=> 35,
                'code' => '192',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sigowet/Soin',
                'county_id'=> 35,
                'code' => '193',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sotik',
                'county_id'=> 36,
                'code' => '194',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chepalungu',
                'county_id'=> 36,
                'code' => '195',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bomet East',
                'county_id'=> 36,
                'code' => '196',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bomet Central',
                'county_id'=> 36,
                'code' => '197',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Konoin',
                'county_id'=> 36,
                'code' => '198',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lugari',
                'county_id'=> 37,
                'code' => '199',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Likuyani',
                'county_id'=> 37,
                'code' => '200',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Malava',
                'county_id'=> 37,
                'code' => '201',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lurambi',
                'county_id'=> 37,
                'code' => '202',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Navakholo',
                'county_id'=> 37,
                'code' => '203',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mumias West',
                'county_id'=> 37,
                'code' => '204',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mumias  East',
                'county_id'=> 37,
                'code' => '205',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Matungu',
                'county_id'=> 37,
                'code' => '206',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Butere',
                'county_id'=> 37,
                'code' => '207',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Khwisero',
                'county_id'=> 37,
                'code' => '208',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Shinyalu',
                'county_id'=> 37,
                'code' => '209',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ikolomani',
                'county_id'=> 37,
                'code' => '210',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vihiga',
                'county_id'=> 38,
                'code' => '211',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sabatia',
                'county_id'=> 38,
                'code' => '212',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hamisi',
                'county_id'=> 38,
                'code' => '213',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Luanda',
                'county_id'=> 38,
                'code' => '214',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emuhaya',
                'county_id'=> 38,
                'code' => '215',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mt. Elgon',
                'county_id'=> 39,
                'code' => '216',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sirisia',
                'county_id'=> 39,
                'code' => '217',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kabuchai',
                'county_id'=> 39,
                'code' => '218',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bumula',
                'county_id'=> 39,
                'code' => '219',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kanduyi',
                'county_id'=> 39,
                'code' => '220',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Webuye East',
                'county_id'=> 39,
                'code' => '221',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Webuye West',
                'county_id'=> 39,
                'code' => '222',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kimilili',
                'county_id'=> 39,
                'code' => '223',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tongaren',
                'county_id'=> 39,
                'code' => '224',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teso North',
                'county_id'=> 40,
                'code' => '225',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teso South',
                'county_id'=> 40,
                'code' => '226',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nambale',
                'county_id'=> 40,
                'code' => '227',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Matayos',
                'county_id'=> 40,
                'code' => '228',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Butula',
                'county_id'=> 40,
                'code' => '229',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Funyula',
                'county_id'=> 40,
                'code' => '230',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Budalangi',
                'county_id'=> 40,
                'code' => '231',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ugenya',
                'county_id'=> 41,
                'code' => '232',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ugunja',
                'county_id'=> 41,
                'code' => '233',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alego Usonga',
                'county_id'=> 41,
                'code' => '234',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gem',
                'county_id'=> 41,
                'code' => '235',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bondo',
                'county_id'=> 41,
                'code' => '236',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rarieda',
                'county_id'=> 41,
                'code' => '237',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kisumu East',
                'county_id'=> 42,
                'code' => '238',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kisumu West',
                'county_id'=> 42,
                'code' => '239',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kisumu Central',
                'county_id'=> 42,
                'code' => '240',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Seme',
                'county_id'=> 42,
                'code' => '241',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyando',
                'county_id'=> 42,
                'code' => '242',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhoroni',
                'county_id'=> 42,
                'code' => '243',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyakach',
                'county_id'=> 42,
                'code' => '244',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kasipul',
                'county_id'=> 43,
                'code' => '245',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kabondo Kasipul',
                'county_id'=> 43,
                'code' => '246',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Karachuonyo',
                'county_id'=> 43,
                'code' => '247',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rangwe',
                'county_id'=> 43,
                'code' => '248',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Homa Bay Town',
                'county_id'=> 43,
                'code' => '249',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ndhiwa',
                'county_id'=> 43,
                'code' => '250',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mbita',
                'county_id'=> 43,
                'code' => '251',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Suba',
                'county_id'=> 43,
                'code' => '252',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rongo',
                'county_id'=> 44,
                'code' => '253',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Awendo',
                'county_id'=> 44,
                'code' => '254',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Suna East',
                'county_id'=> 44,
                'code' => '255',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Suna West',
                'county_id'=> 44,
                'code' => '256',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Uriri',
                'county_id'=> 44,
                'code' => '257',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyatike',
                'county_id'=> 44,
                'code' => '258',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kuria West',
                'county_id'=> 44,
                'code' => '259',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kuria East',
                'county_id'=> 44,
                'code' => '260',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bonchari',
                'county_id'=> 45,
                'code' => '261',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'South Mugirango',
                'county_id'=> 45,
                'code' => '262',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bomachoge Borabu',
                'county_id'=> 45,
                'code' => '263',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bobasi',
                'county_id'=> 45,
                'code' => '264',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bomachoge Chache',
                'county_id'=> 45,
                'code' => '265',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyaribari Masaba',
                'county_id'=> 45,
                'code' => '266',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyaribari Chache',
                'county_id'=> 45,
                'code' => '267',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitutu Chache North',
                'county_id'=> 45,
                'code' => '268',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kitutu Chache South',
                'county_id'=> 45,
                'code' => '269',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyamira North',
                'county_id'=> 46,
                'code' => '270',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nyamira South',
                'county_id'=> 46,
                'code' => '271',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Borabu Masaba',
                'county_id'=> 46,
                'code' => '272',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'North Manga',
                'county_id'=> 46,
                'code' => '273',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Westlands',
                'county_id'=> 47,
                'code' => '274',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dagoreti North',
                'county_id'=> 47,
                'code' => '275',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dagoretti South',
                'county_id'=> 47,
                'code' => '276',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Langata',
                'county_id'=> 47,
                'code' => '277',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kibra',
                'county_id'=> 47,
                'code' => '278',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Roysambu',
                'county_id'=> 47,
                'code' => '279',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kasarani',
                'county_id'=> 47,
                'code' => '280',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ruaraka',
                'county_id'=> 47,
                'code' => '281',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Embakasi South',
                'county_id'=> 47,
                'code' => '282',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Embakasi North',
                'county_id'=> 47,
                'code' => '283',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Embakasi Central',
                'county_id'=> 47,
                'code' => '284',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Embakasi East',
                'county_id'=> 47,
                'code' => '285',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Embakasi West',
                'county_id'=> 47,
                'code' => '286',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Makadara',
                'county_id'=> 47,
                'code' => '287',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kamukunji',
                'county_id'=> 47,
                'code' => '288',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Starehe',
                'county_id'=> 47,
                'code' => '289',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mathare',
                'county_id'=> 47,
                'code' => '290',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        SubCounty::insert($subcounties);
    }
}
