version: 0.2

phases:
 install:
  runtime-versions:
   nodejs:10
  commands:
    - printenv
    - echo "installing something"
 pre_build:
     commands:
      - echo "we are in pre-build stage"
     build:
      commands:
        - echo "we are in the build block"
        - echo "we will run some tests"
        - grep -Fq "Congratulations" index.html
 post_build:
   commands:
      - echo "we are in post-build stage"
      
artifacts:
 files:
  - '**/*'
 name: my-msuredemo-artifacts
        
     
